#!/usr/bin/env ruby
# -*- mode: ruby -*-
require "rubygems"
require "rake"


namespace :interval do
  task :purge do
    sh "rm -rf .emacs*"
  end
end

task :update => ["interval:purge"] do
  sh "cp ~/.emacs ./"
  sh "cp -r ~/.emacs.d ./"
  sh "cp ~/.emacs_bash ./"
end


task :install do
  sh "cp ./.emacs ~/"                                                                                                                                                                                     
  sh "cp -r ./.emacs.d ~/"
  sh "cp ./.emacs_bash ~/"
end
